#==========================- Pre-initialisation parameters -=========================



/run/initialize
/run/verbose 2

/gps/particle gamma
#/gps/ion 9 18 0 0 # F-18
/gps/particle e+
/gps/energy 0 keV
/gps/pos/type Volume
#/gps/pos/shape Sphere
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 0 cm 
/gps/pos/radius 3.2 mm
/gps/pos/halfz  3 mm

/gps/ang/type iso
#/random/setSeeds  1 2 

/run/beamOn 100000000
#/control/execute vis.mac
